{% set name = "napari-animation" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_animation-{{ version }}.tar.gz
  sha256: 82f0888cc56bb164d7d3d129b7fb6482dca268ff15f4fc0fb49a1996b3864bcc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - imageio
    - imageio-ffmpeg
    - napari
    - npe2
    - numpy
    - python >=3.8
    - qtpy
    - scipy
    - superqt
    - tqdm >=4.56.0

test:
  imports:
    - napari_animation
  commands:
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/napari/napari-animation
  summary: A plugin for making animations in napari
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    napari-animation is a plugin for making animations in napari.

extra:
  recipe-maintainers:
    - alisterburt
    - goanpeca
    - jaimergp
    - jni
    - sofroniewn
